#ifndef ../../../bed/bedrc.hRC_H_
#define ../../../bed/bedrc.hRC_H_ 1

//
// BSA-WINAPI  compiled resources
//
// Generated by BSARC
//

extern "C" {
extern int         _cb_zg_resources;
extern unsigned char _zg_resources[];
}
  
#endif
