
SOURCES		=	\
			persistx.cpp					\
			persist.cpp						\
			perstini.cpp					\
			perstreg.cpp					\
			perstxml.cpp					\
			perstrc.cpp

SOURCES+=		 \
			persistx.h						\
			makefile						\
			bsapersist.dsp
			
include $(ROOT)/build/template.mak
