export ROOT=../../..
export HOST_OS=OSX
export TARGET_ARCH=x86_64
export TARGET_OS=OSX
export HOST_ARCH=x86_64
APPLICATIONS=bcalc
export EXTRA_DEFINES+=UNICODE
export SYSTEM_FRAMEWORKS=Cocoa
include $(ROOT)/build/template.mak
